# Generated by Django 5.2.2 on 2025-06-19 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioadoptante',
            name='preferencias',
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('tamaño', models.CharField(blank=True, max_length=50)),
                ('acepta_no_vacunados', models.CharField(blank=True, max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='adopcion.usuarioadoptante')),
            ],
        ),
    ]
